HAI 1.2

HOW IZ I SOLVEMEFIRST YR NUM1 AN YR NUM2
  FOUND YR SUM OF NUM1 AN NUM2
IF U SAY SO

I HAS A Num1
I HAS A Num2
I HAS A Res
GIMMEH Num1
GIMMEH Num2
Res R I IZ SOLVEMEFIRST YR Num1 AN YR Num2 MKAY
VISIBLE Res
KTHXBYE
