HAI 1.2
CAN HAS STDIO?
I HAS A numbur ITZ A NUMBR
GIMMEH numbur
numbur R MAEK numbur A NUMBR

IM IN YR LOOP UPPIN YR i TIL BOTH SAEM i AN 10
    VISIBLE SMOOSH numbur AN " x " AN SUM OF i AN 1 AN " = " AN PRODUKT OF numbur AN SUM OF i AN 1 MKAY
IM OUTTA YR LOOP

KTHXBYE
